name = "american-pos-main"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "american-pos-db"
database_id = "87c7f6b4-3923-4df4-a4f5-186db8cff3ea"
